apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: streams-kustomize
resources:
  - kafka/kafka.yaml
  - kafka/user.yaml
  - kafka/topic.yaml
  - kafka/mm2.yaml
  - submariner/serviceExport.yaml